# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 09:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('articletitle', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='文章标题')),
                ('articlecontent', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章详情')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModels', verbose_name='作者id')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='TagModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('tagname', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='标签名')),
                ('parentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.TagModels', verbose_name='父id')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='articlemodels',
            name='tagid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.TagModels', verbose_name='标签id'),
        ),
    ]
