# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodels',
            name='parentid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='article.TagModels', verbose_name='父id'),
        ),
    ]
