# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190211_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodels',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.TagModels', verbose_name='父id'),
        ),
    ]
