# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190211_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodels',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModels', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='articlemodels',
            name='tagid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.TagModels', verbose_name='标签'),
        ),
    ]
