# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0005_auto_20190211_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleModels', verbose_name='评论文章')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModels', verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论区管理',
                'verbose_name_plural': '评论区管理',
                'db_table': 'comment',
            },
        ),
    ]
